#!/bin/bash

## Configuration, will be overrided by config file
	
# Notification title when grim successfully saved
succ_noTit="Kasha!"

# Notification text when grim successfully saved
succ_noTex="Screenshot saved!"

# Notification text when grim successfully saved
succ_noTex_cp="Screenshot copied to clipboard!"

# Notification title when QR Scanned and copied
succ_noTit_sccop="QR Code scan result"

# Prompt dialog title when qr code scanned
dia_tit="Prompt"

# Prompt dialog text when qr code scanned
dia_tex="QR Code detected, and sucessfully scanned\n Do you want to copy the scan result instead?"

# Prompt dialog copy image button
dia_imgcop_butt="Copy image"

# Prompt dialog copy image button
dia_sccop_butt="Copy scan result"

# grim save dir
sv_dir="/home/$USER/Pictures/Screenshots/"

# grim file name
sv_name="$(date)"

## Overriding Config file (will auto make them)

	con_dir=/home/$USER/.config/eses-w
	con_file=/home/$USER/.config/eses-w/config

	if [ -d "$con_dir" ]; then
		test -f "$con_file" || sed -n "5, 33p" eses-w > $con_file
	else
		mkdir $con_dir
		sed -n "5, 33p" eses-w > $con_file
	fi

	source $con_file

## Making sure save directory is exist

	test -d "$sv_dir" || mkdir $sv_dir

## Code

case "$1" in
	--select)
		grim -g "$(slurp)" "$sv_dir$sv_name"
		notify-send -t 1000 "$succ_noTit" "$succ_noTex"
		;;
	--whole)
		grim "$sv_dir$sv_name"
		notify-send -t 1000 "$succ_noTit" "$succ_noTex"
		;;
	--whole_cp)
		grim - | wl-copy -t image/png
		notify-send -t 1000 "$succ_noTit" "$succ_noTex_cp"
		;;
	--select_cp)
		tmp_file="/tmp/qr.png"

		# maimselect > "$tmp_file"
		grim -g "$(slurp)" "$tmp_file"
		scanresult=$(zbarimg --quiet --raw "$tmp_file" | tr -d '\n')

		if [ -z "$scanresult" ]; then
			wl-copy -t image/png < $tmp_file
			notify-send "$succ_noTit" "$succ_noTex_cp"
		else
			ask=$(zenity --question --text="$dia_tex" --title="$dia_tit" --icon-name=info --no-wrap --ok-label="$dia_sccop_butt" --cancel-label="$dia_imgcop_butt" --ellipsize)
			if [ $? = "0" ]; then
				echo "$scanresult" | wl-copy
				convert $tmp_file -resize 75x75 "$tmp_file"
				notify-send -i "$tmp_file" "$succ_noTit_sccop" "$scanresult"
			elif [ $? = "1" ]; then
				wl-copy -t image/png < $tmp_file
				notify-send -t 1000 "$succ_noTit" "$succ_noTex_cp"
			fi
		fi
		;;
esac	
